# Generated by Django 3.2.13 on 2022-06-28 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_r', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='raza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raza', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='upp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(unique=True)),
                ('name_u', models.CharField(max_length=255)),
                ('prop', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arete', models.IntegerField(unique=True)),
                ('edad', models.IntegerField()),
                ('raza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.raza')),
                ('ubication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.ranch')),
                ('upp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.upp')),
            ],
        ),
    ]
